### ISSUE TITLE
Unable to set required fields

### ISSUE THREAD

**Issue by dvdprr6** [GillianPerard/typescript-json-serializer#109]
It there a way to set required fields when using deserialize?

For example if I have this object
```javascript
@Serializable()
class User{
  @JsonProperty({ name: 'email' })
  private _email: string
  @JsonProperty({ name: 'password' })
  private _password: string

  constructor(email: string, password: string){
    this._email = email
    this._password = password
  }

  public get email(): string{
    return this._email
  }

  public set email(email: string){
    this._email = email
  }
```
I tried to deserialize a json which only has password ```{ password: 'password123' }``` 

```javascript
const user = deserialize<User>(json, User)
```

The result model would return the email field as  undefined.

I tried to use a predicate like this 
```javascript 
@JsonProperty({ name: 'email', predicate: emailPredicate })
``` 
where
```javascript
const emailPredicate = (_email: any) => {
  if(_email instanceof String){
    return String
  }else if(_email === undefined){
    throw new Error()
  }else {
    throw new Error()
  }
}
```

but it still returns a field email as undefined. Perhaps my approach is incorrect?

**Comment by GillianPerard** [comment]
Hi, you got a good idea but this lib is not really a validator lib or a filtering lib. It is just a conversion lib.

I could implement a filter like `required` but the array you `deserialize` will be altered and when you'll use `serialize` you get a different array than from the beginning because I can't populate your array again with the objects previously removed. 

I suggest that you must filter your objects before `deserialization` if possible (to avoid treatment) else just after.

Thank you very much to use my lib and provide some feedbacks here 😊
