### ISSUE TITLE
Issue with dates serialization and deserialization

### ISSUE THREAD

**Issue by ArnaudGallardo** [GillianPerard/typescript-json-serializer#115]
Hi everyone,

I have a small issue with date serialization and deserialization in my current project, I made a reproducer that you can find on [stackblitz](https://stackblitz.com/edit/typescript-npyesc?devtoolsheight=33&file=index.ts).

Basically, I'm trying to serialize and deserialize an object containing a Date using custom functions for _onDeserialize_ and _onSerialize_ (I have some custom Date magic in my app that I removed from the reproducer to make it more readable).

The problem is that the _onSerialize_ function receives a string and not a Date and I don't understand why. I can workaround the problem by re-creating a Date from the string but I should not have to do that.

Thanks

**Comment by GillianPerard** [comment]
Hi!
Thank you for using my lib, let me check :).

**Comment by GillianPerard** [comment]
Hi, I found a solution so I create new 3.0.0 version because there are some breaking changes!

FYI, with this release I renamed previous functions you could pass to `JsonProperty` decorator to modify the data:
- `onSerialize` => `afterSerialize`
- `onDeserialize` => `beforeDeserialize`
-  `postDeserialize` => `afterDeserialize`

This is more consistent.

A function was missing: `beforeSerialize` (the one you need to achieve the date transformation).

So you can use now:

```ts
  @JsonProperty({ beforeDeserialize: strToDate, beforeSerialize: dateToStr })
  birthDate: Date = new Date();
```

I hope it will fix your problem, thank you again for this issue! 😊

**Comment by ArnaudGallardo** [comment]
It fixed my problem. Thanks for the quick fix and the lib !
