### ISSUE TITLE
[FEAT]: Support for polymorphic deserialization

### ISSUE THREAD

**Issue by Alexander-1vanchenko** [GillianPerard/typescript-json-serializer#199]
### Description

**Use-case example:**
Suppose we have a super-type _Foo_  which has a bunch of subtypes _FooA, FooB, etc_. that differ in their properties and behavior.

_Foo_ is structured as a tree, so that its every instance contains a link to an array _Foo[]_ (with 0 or more _Foo_).

It would be nice if it would be possible to discriminate somehow between subtypes while paring Foo.

There are JSON libraries for other languages that support such feature. For instance, [Jackson](https://cowtowncoder.medium.com/jackson-2-12-most-wanted-1-5-deduction-based-polymorphism-c7fb51db7818) has annotations @JsonTypeInfo @JsonSubTypes which allow to provide metadata specifying the list of subtypes and how to decide which of them to use.

I know that instead of subtypes, I can define a bunch of optional properties inside _Foo_, dump all the methods into it and plug conditional logic into these methods. But it would be messy.

Is there any workaround that would allow leveraging the polymorphism?

Thanks

**Comment by GillianPerard** [comment]
Hi, thank you for using my lib.

The issue comes from Typescript, I can't detect the actual type, it only detects the one I describe in my class; here the parent class, not the type of the instance (child class).

But you can create a predicate for the type where you could choose the correct type according to a property it owns.
 Check this example: https://stackblitz.com/edit/typescript-zvgaok?file=index.ts
